//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_wcftask.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/EmpManagement_WCF")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empID {
            get {
                return this.empIDField;
            }
            set {
                if ((object.ReferenceEquals(this.empIDField, value) != true)) {
                    this.empIDField = value;
                    this.RaisePropertyChanged("empID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEmployeeRecord", ReplyAction="http://tempuri.org/IService1/AddEmployeeRecordResponse")]
        string AddEmployeeRecord(UI_wcftask.ServiceReference1.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEmployeeRecord", ReplyAction="http://tempuri.org/IService1/AddEmployeeRecordResponse")]
        System.Threading.Tasks.Task<string> AddEmployeeRecordAsync(UI_wcftask.ServiceReference1.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployeeRecords", ReplyAction="http://tempuri.org/IService1/GetEmployeeRecordsResponse")]
        UI_wcftask.ServiceReference1.Employee GetEmployeeRecords(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployeeRecords", ReplyAction="http://tempuri.org/IService1/GetEmployeeRecordsResponse")]
        System.Threading.Tasks.Task<UI_wcftask.ServiceReference1.Employee> GetEmployeeRecordsAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRecords", ReplyAction="http://tempuri.org/IService1/DeleteRecordsResponse")]
        string DeleteRecords(UI_wcftask.ServiceReference1.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRecords", ReplyAction="http://tempuri.org/IService1/DeleteRecordsResponse")]
        System.Threading.Tasks.Task<string> DeleteRecordsAsync(UI_wcftask.ServiceReference1.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateEmployeeContact", ReplyAction="http://tempuri.org/IService1/UpdateEmployeeContactResponse")]
        string UpdateEmployeeContact(UI_wcftask.ServiceReference1.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateEmployeeContact", ReplyAction="http://tempuri.org/IService1/UpdateEmployeeContactResponse")]
        System.Threading.Tasks.Task<string> UpdateEmployeeContactAsync(UI_wcftask.ServiceReference1.Employee emp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : UI_wcftask.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<UI_wcftask.ServiceReference1.IService1>, UI_wcftask.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddEmployeeRecord(UI_wcftask.ServiceReference1.Employee emp) {
            return base.Channel.AddEmployeeRecord(emp);
        }
        
        public System.Threading.Tasks.Task<string> AddEmployeeRecordAsync(UI_wcftask.ServiceReference1.Employee emp) {
            return base.Channel.AddEmployeeRecordAsync(emp);
        }
        
        public UI_wcftask.ServiceReference1.Employee GetEmployeeRecords(string id) {
            return base.Channel.GetEmployeeRecords(id);
        }
        
        public System.Threading.Tasks.Task<UI_wcftask.ServiceReference1.Employee> GetEmployeeRecordsAsync(string id) {
            return base.Channel.GetEmployeeRecordsAsync(id);
        }
        
        public string DeleteRecords(UI_wcftask.ServiceReference1.Employee emp) {
            return base.Channel.DeleteRecords(emp);
        }
        
        public System.Threading.Tasks.Task<string> DeleteRecordsAsync(UI_wcftask.ServiceReference1.Employee emp) {
            return base.Channel.DeleteRecordsAsync(emp);
        }
        
        public string UpdateEmployeeContact(UI_wcftask.ServiceReference1.Employee emp) {
            return base.Channel.UpdateEmployeeContact(emp);
        }
        
        public System.Threading.Tasks.Task<string> UpdateEmployeeContactAsync(UI_wcftask.ServiceReference1.Employee emp) {
            return base.Channel.UpdateEmployeeContactAsync(emp);
        }
    }
}
